# Generated by Django 2.2 on 2019-04-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('adress', models.CharField(max_length=400)),
                ('starting_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField()),
                ('organizer', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=15000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
